apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: go-service-template
  title: "Create Go Service"
  description: |
    Scaffold a new Go microservice with Kubernetes and Helm support.
  tags:
    - go
    - kubernetes
    - helm
spec:
  owner: platform-engineering
  type: service
  system: microservice

  parameters:
    - title: "Service Details"
      required: ["component_id", "owner", "description"]
      properties:
        component_id:
          title: "Service Name"
          type: string
          description: "Enter the name of the service"
          pattern: "^[a-zA-Z0-9_-]+$"
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        description:
          title: "Description"
          type: string
          description: "Short description of the service"

  steps:
    - id: fetch-template
      name: Fetch Skeleton Template
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./
        cookiecutterCompat: true
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        #allowedHosts: ["github.com"]
        repoUrl: github.com?repo=${{ parameters.component_id }}&owner=simontakite
        defaultBranch: main
        repoVisibility: public
    # The final step is to register our new component in the catalog.
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  # some outputs which are saved along with the job for use in the frontend
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
