apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id | trim }}
  {%- if values.description %}
  description: ${{ values.description | trim }}
  {%- endif %}
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: simontakite/${{ values.component_id | trim }}
  tags:
    - go
    - helm
    - service
  links:
    - url: https://github.com/simontakite/${{ values.component_id | trim }}
      title: ${{ values.component_id | trim }} app
      icon: dashboard
spec:
  type: website
  lifecycle: experimental
  owner: ${{ values.owner | trim }}
  system: microservice
