apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id | trim }}
  {%- if values.description %}
  description: ${{ values.description | trim }}
  {%- endif %}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - go
    - helm
    - service
spec:
  type: website
  lifecycle: experimental
  owner: ${{ values.owner | trim }}
  system: microservice
