apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - go
    - helm
    - service
spec:
  type: website
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  system: microservice
