# site_name: '${{values.component_id | dump}} Documentation'

# nav:
#   - Home: index.md

# plugins:
#   - techdocs-core

# repo_url: https://github.com/simontakite/go-app/tree/main/ 
# edit_uri: https://github.com/simontakite/go-app/edit/main/docs

---
# Project information
site_name: ${{ values.component_id | trim }} Documentation
site_url: https://github.com/simontakite/${{ values.component_id | trim }}
site_author: Maintainers

# Repository
repo_name: go-app
#repo_url: https://github.com/[YOUR_GITHUB_ID]/[YOUR-REPOSITORY-NAME]
repo_url: https://github.com/simontakite/${{ values.component_id | trim }}
#edit_uri: edit/master/[YOU-DOCUMENTATION_FOLDER]
edit_uri: https://github.com/simontakite/${{ values.component_id | trim }}/edit/main/docs
docs_dir: docs

# Navigation
nav:
  - Welcome:
    - Overview: index.md   
  
## DO NOT CHANGE BELOW THIS LINE

# Copyright
# TBD

# Theme
theme:
  name: mkdocs
  # font:
  #   text: IBM Plex Sans
  #   code: IBM Plex Mono
  # icon:
  #   logo: material/library
  # features:
  #   # - navigation.tabs
  #   - navigation.instant
  #   - navigation.expand
  # palette:
  #   scheme: default
  #   primary: blue
  #   accent: blue

# Plugins
plugins:
  - search
  - techdocs-core

# Customization
# TBD

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true