site_name: '${{values.component_id | dump}} Documentation'

nav:
  - Home: index.md

plugins:
  - techdocs-core

repo_url: https://github.com/simontakite/go-app/tree/main/ 
edit_uri: https://github.com/simontakite/go-app/edit/main/docs
